---
# tasks file for a35a0d3
- name: Copy docker files specific to a35a0d3
  copy:
    src: "files/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian'

# - name: Start truedesk
#   docker_compose:
#     project_src: /opt/8118-truedesk/
#     state: present
#   #vars:
#     #ansible_python_interpreter: /usr/bin/python3
