---
- hosts: 127.0.0.1
  gather_facts: no
  
  tasks:
    - name: check current system date
      command: date
      register: date

    - name: pring the current system date
      debug:
        var: date.stdout

  vars_prompt:
    - name: share_user
      prompt: "what is ur username?"

    - name: share_pass
      prompt: "whats ur passwd?"
      private: yes