---
# tasks file for ansible
- name: Install pip
  apt:
    name: 
      - pip
    state: present
  become: yes
  when:  ansible_hostname == 'virthost01' or ansible_hostname == '4a999ff'
    
- name: Remove apt ansible
  apt:
    name: 
      - ansible
    state: absent
  become: yes

- name: install ansible using pip
  pip:
    name:  
      - ansible
    state: present
  become: yes
  when:  ansible_hostname == 'virthost01'