---
all:
  children:
    ionos:
      hosts:
        d86df44.online-server.cloud:
        112e275.online-server.cloud:
        a35a0d3.online-server.cloud:
        4a999ff.online-server.cloud:
      children:
        allservers:
          hosts: 
            msrv02.skyline.lan:
            d86df44.online-server.cloud:
            112e275.online-server.cloud:
            a35a0d3.online-server.cloud:
            4a999ff.online-server.cloud:
            solr.skyline.lan:
            jenkins.skyline.lan:
            gitlab.skyline.lan: 
             # ansible_host: 192.168.14.223:
        swarm:
          hosts:
            d86df44.online-server.cloud:
            112e275.online-server.cloud:
            a35a0d3.online-server.cloud: # master
            #b0235ee.online-server.cloud:
        sandbox:
          hosts:
            #msvr02.skyline.lan:
            d86df44.online-server.cloud:
            112e275.online-server.cloud:
            a35a0d3.online-server.cloud:
            #4a999ff.online-server.cloud:
######
####      
    local:
      hosts:
        virthost01.skyline.lan:
        #localhost: # having this enable will connect to the localhost twice, which will work but the hostname update for this 'localhost' will fail.
####
    vms:
      hosts:
        #solr.skyline.lan: 
        #  ansible_host: 192.168.14.223

