pipeline {
    agent { 
        node {
            label 'docker-agent-ansible'
            }
      }
    triggers {
        pollSCM '* * * * *'
    }
    environment {
        ANSIBLE_VAULT = ''
    }
    stages {
        stage('Get Credentials') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ansible-vault', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    // Access credentials as environment variables
                    sh 'echo "Username: $USERNAME Password: $PASSWORD"'
                    
                    // Save credentials in a variable
                    script {
                        env.ANSIBLE_VAULT = "${PASSWORD}"
                    }
                    sh "touch ./.vaultpass"
                    sh "chown jenkins:jenkins ./.vaultpass"
                    sh "chmod 640 ./.vaultpass"                    
                    sh "echo '${PASSWORD}' > ./.vaultpass"
                }
            }
        }
        stage('Ansible | Provision') {
            steps {
                echo "Provision..."
                sh '''
                pwd
                cd mySetupRoles
                pwd
                which ansible-playbook
                echo "" > /home/jenkins/log/ansible.log
                /usr/bin/ansible-playbook --vault-id ./.vaultpass ./run-provisions.yml
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                #cd myapp
                #python3 hello.py
                #python3 hello.py --name=Brad
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}