pipeline {
    agent { 
        node {
            label 'docker-agent-ansible'
            }
      }
    triggers {
        pollSCM '* * * * *'
    }
    environment {
        ANSIBLE-VAULT = credentials('ansible-vault')
        
    }
    stages {
        stage('Ansible | Provision') {
            steps {
                echo "Provision..."
                sh '''
                pwd
                cd mySetupRoles
                pwd
                which ansible-playbook
                touch /home/jenkins/log/ansible.log
                /usr/bin/ansible-playbook --vault-id 'ANSIBLE-VAULT' ./run-provisions.yml
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                #cd myapp
                #python3 hello.py
                #python3 hello.py --name=Brad
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}