pipeline {
    agent { 
        node {
            label 'docker-agent-ansible'
            }
      }
    triggers {
        pollSCM 'H * * * *'
    }
    environment {
        ANSIBLE-VAULT = ''
    }
    stages {
        stage('Example') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ansible-vault', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    // Access credentials as environment variables
                    sh 'echo "Username: $USERNAME Password: $PASSWORD"'
                    
                    // Save credentials in a variable
                    script {
                        env.ANSIBLE-VAULT = "${PASSWORD}"
                    }
                }
            }
        stage('Ansible | Provision') {
            steps {
                echo "Provision..."
                sh '''
                pwd
                cd mySetupRoles
                pwd
                which ansible-playbook
                touch /home/jenkins/log/ansible.log
                /usr/bin/ansible-playbook --vault-id ${ANSIBLE-VAULT} ./run-provisions.yml
                '''
            }
        }
        stage('Test') {
            steps {
                echo "Testing.."
                sh '''
                #cd myapp
                #python3 hello.py
                #python3 hello.py --name=Brad
                '''
            }
        }
        stage('Deliver') {
            steps {
                echo 'Deliver....'
                sh '''
                echo "doing delivery stuff.."
                '''
            }
        }
    }
}