---
- hosts: allservers
  remote_user: ibrahim
  ##become: true
  become_user: root
  #gather_facts: true
  vars_files:
    - ansible-vault.yml 
  roles:
   - provisions
   - ssh
   - dockers

- hosts: cloud
  remote_user: ibrahim
  ##become: true
  become_user: root
  #gather_facts: true
  vars_files:
    - ansible-vault.yml 
  roles:
   - apt-packages # 4a999ff should not be part of this hosts
