---
- name: PROVISIONS | First time Initialisation
  hosts: allservers
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - provisions
    - ssh

- name: PROVISIONS | First time Initialisation - LOCALHOST
  hosts: local
  connection: local
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - provisions
    - ssh

# - name: PROVISIONS | First time Initialisation - VMS
#   hosts: vms
#   #connection: local
#   remote_user: vagrant
#   #remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - provisions
#     - ssh

# complete, tested and working
