---
- name: HOSTNAME | Initialisation
  hosts: allservers
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - hostname
 
- name: HOSTNAME | Initialisation - LOCALHOST
  hosts: local
  connection: local
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    #- hostname # TODO fix the error here
  
  # complete, tested and working
  