---
- name: DOCEKERS | Initialisation
  hosts: allservers
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - dockers

- name: DOCEKERS | Initialisation - LOCALHOST
  hosts: local
  connection: local
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - dockers

# complete, tested and working
