hostname_additional_hosts:
  - ip_address: 217.160.100.209
    hostname: a35a0d3.online-server.cloud
    hostname_short: "a35a0d3"
  # - ip_address: 5.6.7.8
  #   hostname: b.example.com
  #   hostname_short: b 
  #
apt_host_packages_list:                   # Install Host Specific Packages
- rsync
#
dkr_copy_etx_files: yes                   # # Copy extended docker files to target host