hostname_additional_hosts:
  - ip_address: 192.168.14.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.77.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01
  - ip_address: 192.168.8.254
    hostname: virthost01.skyline.lan
    hostname_short: virthost01








# 127.0.0.1       localhost
# 127.0.1.1       virthost01.skyline.lan  virthost01

# # The following lines are desirable for IPv6 capable hosts
# ::1     localhost ip6-localhost ip6-loopback
# ff02::1 ip6-allnodes
# ff02::2 ip6-allrouters